### PR TITLE
QIP - Better format of wallet addresses

### PR DESCRIPTION
**Pull request by Robyer**

### CODE REVIEW

**Comment by CrypTrip** [comment]
I'll support this, ease of recognition will help speed up visual address audits and reduce losses from mishap.

**Comment by surg0r** [comment]
I would certainly support a shorter less unwieldy address format.

I think it would be worth hearing @cyyber thoughts on this too.

**Comment by cyyber** [comment]
I am in complete favor of this QIP. The address is still human readable but shorter, most likely to result into less human errors compared to existing address length.

**Comment by successor1** [comment]
I do support this QIP.

**Comment by bsnoot0** [comment]
I support this QIP

**Comment by OTDtoGitHub** [comment]
Feels right and most of the experts aknowledge is a better format.
Also the update window at the same time with the ZOND (testnet) release can provide a good opportunity to test it.

**Pull request merged**
