### PR TITLE
Implement privacy feature for QRL

### PR DESCRIPTION
**Pull request by successor1**

### CODE REVIEW

**Review by jackalyst — CHANGES_REQUESTED** [review]
Suggested edit: 
```---
qip: 015
layer: na
title: "Implement privacy feature for QRL"
author: sync
comments-summary: 
comments-uri: https://github.com/theQRL/qips/pull/31
status: proposal/open
type: discussion
created: 2021-05-09
---

# Implement privacy feature

## Abstract

QRL currently has no privacy features. This means ***every transaction can be followed through the blockchain***. The identity of the original wallet holder can be revealed this way by for example tracing the transaction back to KYC required exchanges.

## Motivation

QRL adding privacy features will most likely attract a new target audience: privacy conscious people.

***Edward Snowden: "Arguing that you don't care about the right to privacy because you have nothing to hide is no different than saying you don't care about free speech because you have nothing to say"***

## Implementation

Privacy as an optional feature is no privacy at all so would need to be the default transaction type. 

See Monero's privacy features, such as:

- Stealth addresses
- Untracable transaction outputs
- Confidential transactions (hide amount sent)
- TOR/onion (or similar) network layer.

## Considirations

This will most likely require a hardfork.

Bittrex doesn't allow privacy coins, this means that QRL will be removed from Bittrex. We have to find an alternative exchanges.

Other exchange(s):
Binance, Tradeogre, Uniswap or other decentralized exchanges.```

**Review by successor1 — COMMENTED** [review]
Updated proposal

**Review by jackalyst — APPROVED** [review]

**Comment by Ottslayer** [comment]
I think this is definately a discussion we all should have.
But I do not think that this is the time right now.
What I see as priorities before this discussion are:

-enqlave
-more exchanges
-pos
-smart contracts

I expect enqlave pos and smart contracts to bring much more attention to exchanges, and and a result bringing more leverage to the exchange situation itself. 

I do think that these 4 points are way more important than privacy features, and would hate to see the development of these points delayed because of another hardfork

**Comment by successor1** [comment]
> 
> 
> I think this is definately a discussion we all should have.
> But I do not think that this is the time right now.
> What I see as priorities before this discussion are:
> 
> -enqlave
> -more exchanges
> -pos
> -smart contracts
> 
> I expect enqlave pos and smart contracts to bring much more attention to exchanges, and as a result to bring more leverage to the exchange situation itself.
> 
> I do think that these 4 points are way more important than privacy features, and would hate to see the development of these points delayed because of another hardfork

I personally think security & privacy go well together. PoS and improvement in scalability should be priority (this makes it more usable), then privacy features and smart contracts. Speed should be no priority, in my opinion because this is a longterm project.

**Comment by Ottslayer** [comment]
OK, my first impression was "no, not another hardfork before pos and smart contracts"

I do understand the appeal of a privacy coin, to be honest, I do not have a definitive opinion right now about implementing privacy features.
my biggest fear right now is that there is another delay in either pos or smart contracts. 

to have a more definitive opinion about privacy features I think I would like to wait for a more regulated crypto environment in the US. 
The biggest trading volume still is being generated in the USA and I would not like to exclude this project of this market because of these features.

**Comment by successor1** [comment]
I don't think regulation should scare us off. Decentralized exchanges should provide another path for the US market to access the market. Monero for example, is still growing strong, regardless of what the US is doing.

**Comment by Ottslayer** [comment]
Monero started out when regulation was not a thing at all and is already a powerhouse in the cryptoworld.
I fear that we might suffocate qrl´s growth early on while qrl is taking a deep breath to scream about the quantum threat in Cryptoworlds face.

If qrl would be a top 50 coin or something, I think I would not be that concerned about qrl being locked out of the US market.

Another possibility would be, like you mentioned, decentralized exchanges to take off.

**Comment by successor1** [comment]
That's an interesting way to look at it. I think it depends on many things, if we decide to add such thing, it won't be available immediately, it will take time to implement. So the question would be, when? What is it's priority? Are there any reliable (decentralized) exchanges? I think a quantum resistant blockchain with privacy features is huge and won't be taken lightly, is my speculation. I can't say about the priority because I'll need more detailed information about the roadmap.

**Comment by Ottslayer** [comment]
I am 100% with you on the priority issue.
As I wrote in the beginning: I see several things atm much higher on the priority list.

**Comment by Fy00zh3n** [comment]
I fully believe this should take 100% priority. "Crypto" began because... privacy. Certainly over POS. The world's Crypto with the strongest encryption but doesn't have sender / receiver privacy does NOT sound like a winning combo. It sounds like something is missing. Privacy is a universal concern in todays world where everyone want to sell your data. True privacy coins are  IMO the future. It's what most people think of when they think of Crypto. The look on people's faces is hilarious when you tell them BTC is NOT a true privacy crypto. It's a bubble burstere...Enclave would be my number 2 and smart contacts. "New People" or "regular people" come to crypto because they hear "privacy". .not because they hear about something called "smart contracts". Everyone understands security and privacy. JMO

**Comment by Ottslayer** [comment]
This taking 100% priority would most certainly hurt the project in this current stage in my opinion. 
It will make it even harder to find exchanges to list. (Bittrex recently got rid of privacy coins)
Also I do not agree that most people come to crypto because of privacy concerns. The majority of people are in it for the money.
most articles don´t even mention privacy:
https://www.digitalistmag.com/digital-economy/2019/12/04/6-reasons-to-invest-trade-in-cryptocurrency-in-2020-06201759/

So, I still stand by what I said. This is a conversation to have when qrl is like a top 50 coin. A well known force in crypto.
If then the majority decides to want to go full privacy it won´t have such a big impact as if it would happen right now if many doors would certainly being closed because of being private.

priority should be 
- enqlave
- pos
- smart contracts

in my opinion

let´s have this conversation much later down the line

**Comment by successor1** [comment]
I do agree that idealism was and still is a big force for projects (Especially community driven projects). I do think adding privacy to QRL, adds immediate use case, especially with the quantum resistant security feature. Many IRC channels, forums, FOSS/linux projects, certainly care about privacy. It's mostly underground, just because it's not mainstream, doesn't mean it's not there. Pushing on idealism, originally attracts more people, with similar ideas, which again drives the price up.

Bittrex is a bad exchange, it requires KYC, it's US based, deposit/withdrawals are not possible for long periods of time. I honestly don't think it's a big loss. Like i mentioned before, we should look at alternatives.

This is why i think it should be higher in the priority list, i would say, before or after PoS. Keep in mind, it will be harder to push big changes, when QRL grows, see other cryptocurrency projects, so it's better to do it now, than later.

**Comment by Fy00zh3n** [comment]
One final thought on this. Perhaps I was a little agressive on the priority. To me it just makes sense to do it now WELL AHEAD of PoS. Probably because I favor hybrid anyway. As for exchanges. That will come in time and doesn't truly equal a coins value just because it's listed on "x" exchange. (just look at Doge with never ending supply) There are tons of shyt coins listed. I'm a HODLr also..so I'm biased on that front too. :) I'm not trying to make some quick cash at the expense of quality and rock solid implementation. Privacy adds quality forever.. exchanges make a few people money quickly now.
IOW..JMO...

**Comment by FrancisErdman1** [comment]
Adam Koltun died of AIDS.

**Comment by Dogknotty** [comment]
Yes, I support this feature.

**Comment by QRLprivate** [comment]
Interesting comments! I also believe that adding privacy feature would be a perfect match with quantum resistance. Sort of crypto safe haven to store/protect value.
POS vs POW I prefer an hybrid approach to increase network security...

**Comment by Spunky7** [comment]
> Suggested edit:
> 
> ```
> qip: 015
> layer: na
> title: "Implement privacy feature for QRL"
> author: sync
> comments-summary: 
> comments-uri: https://github.com/theQRL/qips/pull/31
> status: proposal/open
> type: discussion
> created: 2021-05-09
> ---
> 
> # Implement privacy feature
> 
> ## Abstract
> 
> QRL currently has no privacy features. This means ***every transaction can be followed through the blockchain***. The identity of the original wallet holder can be revealed this way by for example tracing the transaction back to KYC required exchanges.
> 
> ## Motivation
> 
> QRL adding privacy features will most likely attract a new target audience: privacy conscious people.
> 
> ***Edward Snowden: "Arguing that you don't care about the right to privacy because you have nothing to hide is no different than saying you don't care about free speech because you have nothing to say"***
> 
> ## Implementation
> 
> Privacy as an optional feature is no privacy at all so would need to be the default transaction type. 
> 
> See Monero's privacy features, such as:
> 
> - Stealth addresses
> - Untracable transaction outputs
> - Confidential transactions (hide amount sent)
> - TOR/onion (or similar) network layer.
> 
> ## Considirations
> 
> This will most likely require a hardfork.
> 
> Bittrex doesn't allow privacy coins, this means that QRL will be removed from Bittrex. We have to find an alternative exchanges.
> 
> Other exchange(s):
> Binance, Tradeogre, Uniswap or other decentralized exchanges.```
> ```

With blockchain technology, we have the potential to create a more empowering and inclusive internet - what is often referred to as Web3. But current blockchains are public by default, exposing all data to everyone and putting users at risk. In order to enable meaningful use cases and achieve global adoption, users and organizations need control over how their data is used and shared - a concept we call programmable privacy.

**Comment by Spunky7** [comment]
With blockchain technology, we have the potential to create a more empowering and inclusive internet - what is often referred to as Web3. But current blockchains are public by default, exposing all data to everyone and putting users at risk. In order to enable meaningful use cases and achieve global adoption, users and organizations need control over how their data is used and shared - a concept we call programmable privacy.

**Comment by Spunky7** [comment]
Really difficult, personally I originally come to use QRL for its fast transaction speed with QRLprivacy on the horizon at the time, this would make it fantastic as  a payment method. A fast private blockchain. I think privacy will be an important aspect of the future as our freedoms and privacy's are eroded. As more and more things are tracked and your data is collected by various etc

The longer I'm here I'm starting to see QRL is a lot more versatile than just as a payment method, it's more like a highway, with projects built on QRLchain being the service stations along the highway. :) 

If people can understand my analogy :)

Even if QRL does not implement QRLprivacy, I hope projects built on QRLchain will be allowed the choice to implement Quantum Resistance Ledger privacy at the point of token creation.

If Quantum Resistance Ledger does not itself implement Quantum Resistance Ledger Privacy. Then staking is my vote.

**Comment by Spunky7** [comment]
"I hope projects built on Quantum Resistance Ledger chain will be allowed to implement the option to activate Quantum Resistance Ledger Privacy" <- i agree.

**Comment by Spunky7** [comment]
Not every community member is an American. In my country, privacy coins are legal. The Government allowed privacy coins and/or tokens. As we may all know crypto did not originate in America but by a Japanese. 
The act of selfishness is depriving Privacy features in an amazing project because of the laws of a group of individuals which does not govern the laws of some different individuals. 

Quantum Resistance Ledger is not registered in USA but Switzerland.

**Comment by Spunky7** [comment]
Not every community member is an American. In my country, privacy coins are legal. The Government allowed privacy coins and/or tokens. As we may all know crypto did not originate in America but by a Japanese.
The act of selfishness is depriving Privacy features in an amazing project because of the laws of a group of individuals which does not govern the laws of some different individuals.

Quantum Resistance Ledger is not registered in USA but Switzerland. As Offshore Banks In Switzerland.

**Comment by Onlive10** [comment]
> This taking 100% priority would most certainly hurt the project in this current stage in my opinion. It will make it even harder to find exchanges to list. (Bittrex recently got rid of privacy coins) Also I do not agree that most people come to crypto because of privacy concerns. The majority of people are in it for the money. most articles don´t even mention privacy: https://www.digitalistmag.com/digital-economy/2019/12/04/6-reasons-to-invest-trade-in-cryptocurrency-in-2020-06201759/
> 
> So, I still stand by what I said. This is a conversation to have when qrl is like a top 50 coin. A well known force in crypto. If then the majority decides to want to go full privacy it won´t have such a big impact as if it would happen right now if many doors would certainly being closed because of being private.
> 
> priority should be
> 
> * enqlave
> * pos
> * smart contracts
> 
> in my opinion
> 
> let´s have this conversation much later down the line

Yes I agree.

**Comment by Spunky7** [comment]
The Canadian government has me feeling bullish AF on privacy coins!

I cannot wait to preach the gospel of privacy in Ottawa again.

**Pull request merged**
