### PR TITLE
Suggestion for transaction replay protection

### PR DESCRIPTION
**Pull request by surg0r**

### CODE REVIEW

**Comment by cyyber** [comment]
To solve the transaction reply attack following can be done

1> To avoid transaction replay between different networks like Testnet and Mainnet, a new field network id could be added into the Transactions. The nodes running on Mainnet, will only accept any transaction having a network id of the Mainnet. Thus inside the block validation, we need to validate the network id and reject any transaction that belongs to the other network. This will avoid any transaction replay attack from one network to another.

2> There is a possibility of the transaction replay if a fork happens on the same network. Lets take a look to following scenario.
 - Alice signed and broadcasted a transaction to send funds to Bob with OTS index 5 (randomly selected OTS). 
 - The transaction accepted into the block.
 - After some period of time, fork happens and a new chain becomes the mainchain.
 - In the new main chain, for some reason Alice transaction is no more part of the chain.
 - Alice needs to resign and broadcast the transaction. And in this case, if Alice signs the transaction with some different OTS index, say OTS index 8.
 - Alice transaction accepted and becomes the part of the mainchain.
 - If a node still has the transaction, which was the part of the fork and somehow is not the part of the new mainchain. He can replay the transaction on the new mainchain, which can result into double payment to Bob. Assuming Alice has sufficient balance and Alice has not used the OTS index 5.

The chances of occurrence of the above scenario is very low. Though to mitigate this issue, we may add an optional field last transaction hash, which stores the last transaction hash of the signer (addr_from in case signed by slave) address and the signer (addr_from in case signed by slave) signs the transaction that includes the last transaction hash. In that case the nodes will verify if the last transaction hash as mentioned into transaction matches with the last transaction hash found into the signer address (addr_from in case signed by slave). This last transaction hash could be something that can be fetched via Node API or can be manually noted by user each time a transaction is made by them.

**Comment by surg0r** [comment]
Signing the previous transaction hash may not always offer replay protection. If there are no prior transactions after the fork then both chains will have the last transaction hash to reference and without an updated network ID a replay attack may still be possible.

**Comment by cooper7777** [comment]
We should store all output transactions history in all wallets, whenether it is mobile wallet, or desctop wallet, instead of receaving last used OTS from blockchain.
Even lightweight wallet for other blockchains do so(for example Metamask for Ethereum).
In wallets that can't store data(web wallet) we should caution users everytime they unblock their wallets, that they should check transaction history of current wallet, and move funds to another wallet if they don't find in blockchain any transaction that they made.

**Comment by jplomas** [comment]
> In order to counteract malicious nodes that may recieve someone's transactions and not propagate it to the network, we should store all output transactions history in all wallets, whenether it is mobile wallet, or desctop wallet, instead of receaving last used OTS from blockchain.
> Even lightweight wallets for other blockchains do so(for example Metamask for Ethereum).
> In wallets that can't store data(web wallet) we should caution users everytime they unblock their wallets, that they should check transaction history of current wallet, and move funds to another wallet if they don't find in blockchain any transaction that they made.

cooper7777 -- that's a great topic for a separate QIP (and something that had a lot of internal discussion in 2017 prior to mainnet release)

**Comment by cooper7777** [comment]
> > In order to counteract malicious nodes that may recieve someone's transactions and not propagate it to the network, we should store all output transactions history in all wallets, whenether it is mobile wallet, or desctop wallet, instead of receaving last used OTS from blockchain.
> > Even lightweight wallets for other blockchains do so(for example Metamask for Ethereum).
> > In wallets that can't store data(web wallet) we should caution users everytime they unblock their wallets, that they should check transaction history of current wallet, and move funds to another wallet if they don't find in blockchain any transaction that they made.
> 
> cooper7777 -- that's a great topic for a separate QIP (and something that had a lot of internal discussion in 2017 prior to mainnet release)

Got you. Already done.
I just thought about "transaction replay" in more common sense. I mean that user also may replay transaction by himself, than he sees that transaction was not executed.

**Pull request merged**
