### PR TITLE
QIP-007: Support Tokenization of Securities

### PR DESCRIPTION
**Pull request by IMac318**

### CODE REVIEW

**Comment by IMac318** [comment]
I wanted to submit a more formal request for this. I have only a basic understanding of code, and I couldn't find much about the capabilities of QRL smart contracts, so I'm not sure if something like this is possible with the current functionality.

It may also be the case that there are ways to support tokenization of securities other than smart contracts. If so, those methods could be considered as well.

**Comment by hadacnot** [comment]
It may be worth to study the security token standard that you mentioned, developed by polymath on ethereum. They are probably very committed to ethereum, however, knowing that QRL will not have to change its signature scheme during the next ten years is a very big plus for tokenization of securities.

**Comment by surg0r** [comment]
@IMac318 This is an excellent suggestion. 

My first thought is that even though our future smart contract fork is planned to be deliberatively constrained in functionality, it would be possible to achieve the requirements you mention in the QIP for appropriate tokenisation of securities. 

My second thought is that our existing hard-coded token system could be extended to encompass the requirements you mention in the QIP prior to that fork. @cyyber may want to come in on that.

**Comment by atoma01** [comment]
This is a great QIP! I think we would need hashed pre-programmed oracles or something to tackle the oracle problem. The bridge between a open decentralized network, and the real world of identity, law and order needs to be built in a well though out way. Not an easy task.

**Comment by bidulemachin** [comment]
Good idea to think about STO.
In this reflection, it might be interesting to understand what drives some STO projects to build their own blockchain : https://weown.com/blog/5-reasons-we-built-our-own-blockchain/

**Comment by IMac318** [comment]
@surg0r good to hear that. The phrase "smart contract" seems very vague in crypto, so it's good to have that clarification.

@atoma01 @bidulemachin interesting thoughts. Proper implementation is definitely up for debate. It may make sense to use a dual-chain model. Maybe its possible to do a similar thing with ephemeral messaging if privacy is a concern. The benefit of working out a solution to build on top of QRL is obviously its quantum resistance, as it's not easy to build a QR chain from scratch. If STOs ever take off, I don't see it being for a number of years. In my estimation, crypto (probably BTC/ETH or another top coin in particular) would have to gain much more mainstream acceptance for organizations to seriously consider STOs, and it will be longer before widespread use. At that point, maybe 5-10 years or longer, the QC threat will be even more real and severe than it is now (assuming ECDSA isn't already cracked by then, which isn't guaranteed). Therefore, any team trying to tokenize securities should be thinking with QR in mind.

Or at least that's the pitch I would give to potential partners. In any case, glad that the basic functionality exists (and/or could exist). I don't expect the QRL team to spend their resources focusing on security tokens, but it's good to know that other teams can try to build off of QRL for this purpose in the future.

**Pull request merged**
