### PR TITLE
QIP 014 to add NFT support

### PR DESCRIPTION
**Pull request by surg0r**
A QIP to add NFT support to QRL.

Would allow third party projects to immediately begin using NFTs on QRL.

### CODE REVIEW

**Comment by Ottslayer** [comment]
That sounds great!

to clarify: are we talking ocaml NFT possibilities on QRL? so basically partly enabled smart contracts?
Or is the idea more like an enqlave enabled ETH-721 which is somehow bound to a wrapped QRL on ETH?

and also: what time frame are we talking here? I´m guessing another hard fork would be needed for that?
(hence my question about the "partly enabled" smart contracts)
I´m just thinking out loud here, because I guess the reason for adding NFT´s would be the current hype and not "just" adding NFT´s to the smart contract hard fork which will be scheduled supposedly after the pos hard fork.

**Comment by surg0r** [comment]
> That sounds great!
> 
> to clarify: are we talking ocaml NFT possibilities on QRL? so basically partly enabled smart contracts?
> Or is the idea more like an enqlave enabled ETH-721 which is somehow bound to a wrapped QRL on ETH?
> 
> and also: what time frame are we talking here? I´m guessing another hard fork would be needed for that?
> (hence my question about the "partly enabled" smart contracts)
> I´m just thinking out loud here, because I guess the reason for adding NFT´s would be the current hype and not "just" adding NFT´s to the smart contract hard fork which will be scheduled supposedly after the pos hard fork.

This would be immediate changes to allow NFT functionality on chain (qrl-mainnet) right now with no hard fork. It is a bitcoin-like soft forking in of new functionality without breaking anything.
 
Enqlave supports ETH-721 and ERC20 tokens but that is on the ethereum mainnet.

QRL mainnet smart contracts are roadmapped for post-POS hard fork, which is planned for later this year.

**Comment by Ottslayer** [comment]
wow, that blows my mind... again.
soft fork integrating NFT functionality right away sound too good to be true.

how deep of a NFT functionality are we talking here? 
I guess these computer generated "cryptopunk-clones" which are everywhere right now won´t be possible without a hard fork?
(the github repositories as far as I understand them seem to require some kind of programmable connection to the underlying blockchain)

So will these allow basically qrl nft tokens to be created in a basic sense?
Or more variable ones (for the lack of a better understanding i asked about some kind of limited ocaml possibilites with those nfts)

**Comment by snannerb** [comment]
I support this QIP and feel it could do wonders for community engagement and network usage ..Ideally some sort of exchange or NFT viewer could go hand in hand with this and wouldnt mind seing a bounty to persuade development .. I feel this QIP should be a top priority to help with community presence and day to day interest in the project ..NFT's really give an interactive and personal feel to blockchain for users who are not coders.

**Comment by SnootyBoop** [comment]
I SUPPORT this \:D/

**Pull request merged**
